#+OPTIONS: toc:nil num:nil todo:nil
#+LAYOUT: post
#+DATE: 2015-08-25
#+TITLE: Flatland and Spherical Geometry
#+DESCRIPTION:
#+CATEGORIES:

Before passing along my copy[fn:copy] of Flatland to my brother (as he
needs it for a class), I reread it on an airplane. It turns out that
airplanes are the best environment in which to read this book. It's
fortunate that nobody was sitting beside me and asked what I was
reading because they would have gotten the following lecture. You,
dear reader, are not as lucky[fn:lucky].

* Flatland
  Firstly a short synopsis of the book. It was written in 1884 by a
  schoolteacher/theologian Edwin Abbott Abbott[fn:Abbott]. You're
  introduced to a geometrical world from the perspective of "A
  Square", who is a square inhabiting a two-dimensional manifold. He
  describes life in two-dimensions and then is visited by a
  three-dimensional sphere who introduces him to a one-dimensional
  line world (and a zero-dimensional point world) and eventually shows
  him the third-dimension. There's also a good deal more to it,
  including commentary on Victorian society and metaphysical musings.
  It's very short, so there's no reason not to read the [[http://www.gutenberg.org/ebooks/97][entire thing]].
  For those who prefer a movie, apparently such a thing exists and
  actually has Martin Sheen and Kristen Bell as voice actors; I don't
  know how well it tracks the book, but the [[http://www.flatlandthemovie.com/][trailer]] is certainly
  surreal.

* Spherical Geometry
  So what does air travel have to do with anything? It's all about
  geometry. It turns out the spherical geometry is rather strange..
  Here's just a few of the "obvious" geometrical intuitions that not
  necessarily true on a sphere.

** The shortest distance between two points is a line.
   This first is actually true, but it's misleading. When you draw a
   line on a map[fn:map] it's not actually the shortest path between
   the two points. In fact, for a sphere the "lines" are /great
   circles/. These are just the paths you would take if you kept
   walking perfectly straight (from your perspective) until you
   returned to your starting location; any such path is called a
   geodesic. All shortest paths are geodesics but not all geodesics
   are shortest paths. You can see this in spherical geometry because
   while great circles are geodesics, we can choose to go clockwise or
   counterclockwise around the great circle.

** Two points determine a line
   Not necessarily. Consider the North and South pole. There are
   infinitely many lines of longitude (which are great circles)
   extending between the two. In fact any two points which are
   /antipodal/, on the exact opposite side of the sphere, will work.
   If the points aren't antipodal then only two are required.

** There are such things as parallel lines
   This is not the case. One common objection is that lines of
   latitude do not intersect. Looking back at the definition of a
   line, we see that only great circles are lines and thus lines of
   latitude are not lines (in the spherical geometry sense).

** The sum of the angles of a triangle is 180°
   This is where things start getting very interesting. To show that
   this is not true a simple counter-example will suffice. You might
   want to obtain a globe and perform this example for it to sink in.

   #+BEGIN_EXAMPLE
     Start at the intersection of the equator and the prime-meridian. Walk
     counter-clockwise along the equator a quarter of the way around the
     globe. Turn left. Walk until you reach the North Pole. Turn left. Walk
     until you reach the equator at which point you turn left again and
     you're facing the same direction you started.
   #+END_EXAMPLE

   However we turned left three times which results in a sum of
   interior angles of 270°.
   
   It turns out that this is very interesting. We can measure this as
   the angular defect defined as the difference between the sum of the
   angles (in radians) minus the usual value of \pi.. There are several
   things that can be proven about this, the first of which is that
   it's non-negative. All triangles on a sphere have sum of angles
   greater than 180°.

   We can go further and show[fn:proof]. that the area of the triangle
   is the same as the angular defect (for a sphere of radius 1, you
   just scale by $r^{2}$ otherwise) and hence trivially prove the
   previous non-negativity result.

* "Some yet more spacious Space, some more dimensionable Dimensionality"
  Perhaps what I most love about Flatland is that it enthusiastically
  keeps going. You could have gotten a lot of the satire and novelty
  out of the story of introducing "A Square" to the third dimension.
  However, Abbot doesn't stop there. Instead he follows the obvious
  extrapolation and has "A Square" postulate the existence of a 4th
  and 5th dimension, indeed an entire infinite sequence of dimensions.

  #+BEGIN_QUOTE
   And even as we, who are now in Space, look down on Flatland and see
   the inside of all things, so of a certainly there is yet above us
   some higher, purer region, whither thou dost surely purpose to lead
   me - O Thou Whome I shall always call everywhere and in all
   Dimensions, my Priest, Philosopher, and Friend - some yet more
   spacious Space, some more dimensionable Dimensionality, from the
   vantage-ground of which we shall look down together upon the
   revealed insides of solid things, and where thine own intestines,
   and those of thy kindred Spheres, will lie exposed to the View of
   the poor wandering exile from Flatland, to whome so much has
   already been vouchsafed.”
  #+END_QUOTE

  Taking that example to my spherical geometry case, what would be the
  next extension? Suppose instead of a sphere, we were flying on a
  donut or in mathematical terms a torus. The first thing that comes
  to mind with a torus is that there are infinitely many geodesics
  which connect any two distinct points. For a simple example take two
  points on the outer circle of the torus. You can connect them with a
  straight line along the circumference. Or you can connect them with
  a looped line that goes around the ring once, or twice, or three
  times, or however many times you want. All are geodesics and all
  connect the two points.

  Of course, the torus also brings up another interesting point:
  topology[fn:topology]. Abbot describes Flatland as a piece of paper.
  What would be another difference if the Flatlanders lived on a
  torus? For one, they wouldn't have hard edges to their world. They'd
  also find that walking the same direction is faster in some places
  than others, namely when they're on the inside or outside of the
  hole (from our perspective).

  This branches out into figuring out what kinds of surfaces can be
  distinguished by Flatlanders using /intrinsic geometry/, geometry
  that uses only measurements that can be performed on the surface,
  not using the 3rd dimension. This is especially interesting if you
  consider that we're in a putatively 4-dimensional space and
  necessarily need to use intrinsic geometry to figure out what kind
  of space we're in. Experiments have shown that we don't live in a
  Euclidean space, rather we live in a far more interesting curved
  space-time.

* Footnotes
[fn:copy] Don't worry, I found _The Annotated Flatland_ by Ian Stewart
on Amazon, so I'll be trading up.
[fn:lucky] Although I suppose you could stop reading.
[fn:Abbott] Not a typo, his middle and last name are the same
[fn:proof] The proof is very fun and I enjoy performing it with
oranges. If you need a hint, start with cutting the orange in pieces
along the great circles defining the triangle. Also, look up the
definition of a /spherical lune/ and think about its area.
[fn:map] Technically this is not true if you use a Gnomonic
projection, but I'd wager good money that if you know what a Gnomonic
projection is, you are already aware of this fact.
[fn:topology] Apparently this is discussed in _Flatterland: Like
Flatland, Only More So_ also by Ian Stewart.
