#+OPTIONS: toc:nil num:nil todo:nil
#+LAYOUT: post
#+DATE: 2016-06-16
#+TITLE: Three logicians walk into a bar
#+DESCRIPTION: I interpret a simple question very literally. It causes some problems.
#+CATEGORIES:  
#+commentIssueId: 2

#+BEGIN_QUOTE
Attention Conservation Notice: Logic joke with explanation; you had to
have been there
#+END_QUOTE

I had a fun exchange by text today. My father texted both my brother
and myself the following message "Did I borrow [a particular book]
from either of you?". This left me in a bit of a predicament; I don't
have the information to be able to answer his question. For those of
you who are somewhat confused[fn:confused] by this, let me explicate.

The problem hinges on the word "either". Let's look at a table.

|                           | Borrowed from me | Not borrowed from me |
| Borrowed from brother     | Yes              | Yes                  |
| Not borrowed from brother | Yes              | No                   |
#+CAPTION: Responses for "Did I borrow the book from either of you?"

Suppose we're in the first column and thus he did get the book from
me. Then I could answer "yes", and everything is fine[fn:fine].

Now let's consider the case where I don't own the book. Now we're in
the other column. Certainly I know that he didn't borrow the book from
me. But I don't know what books my brother owns. Perhaps my brother
did have the book and my father borrowed it; in this case I should say
"yes". But perhaps my brother didn't have the book; in this case I
should say "no". I have two plausible scenarios with contradicting
responses; I can't respond.

In this situation I can only hope that my brother in fact owned the
book and replied "yes". Otherwise, we'd both be stuck unable to
respond. The question would go unanswered and it would stay in the
front of my mind. Because I can only keep track of [[https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two][7 \pm 2]] things in
working memory, I would be working with at best 88% of my working
memory for the rest of my life. I'm a forgetful person at the best of
times, so with my diminished memory I'll probably forget to turn off
my stove and burn down my apartment complex. All because of a single
careless question.

Given that I'm not typing this from the smoking ruins of an apartment
building, apparently things were resolved. Fortunately I recalled an
old joke

#+BEGIN_QUOTE
Three logicians walk into a bar. The barkeep says, "Do all of you want
a beer?"

The first logician says, "I don't know."

The second logician says, "I don't know."

The third logician says, "Yes!"
#+END_QUOTE

So I replied back with an allusion to this joke and, to my eternal
pride, my brother (who studies math) figured it out and replied "no".
So there was a happy ending after all.

How did my joke reference help? Well, it gave my brother some
information. Namely, it told him that I didn't have enough information
to answer the question myself. The only case in which that's true is
when the book wasn't borrowed from me. This gave my brother the
information needed to confidently answer "no".

I'll leave it to the reader to figure out the connection with the joke.

** Footnotes
[fn:confused] Yes, I basically wrote this up to explain a joke to my father
[fn:fine] I didn't think of this until writing this up, but there's an
unwarranted assumption lurking here. As a family, we've empirically
shown that the fact that a book is sitting on myself does not prevent
other family members from buying the same book. Thus, even if I had a
copy, I still couldn't be certain that my father had borrow it; he
might have just bought it himself. There are, of course, no end to
these sorts of quibbles (see [[https://en.wikipedia.org/wiki/Philosophical_skepticism][philosophical skepticism]]).
